### PR TITLE
Fix password hashing on student creation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rui1974** [comment]
have you installed any other libraries manually ? I get a lot of errors after "npm run frontend"

**Comment by ghost** [comment]
That's a negative, I just checked out the branch and ran "npm install" to get all the dependencies.
On the frontend side, the command to run the frontend by default is "npm run start". 
Inside the package.json file you'll see that this command is defined on the scripts section.

**Comment by rui1974** [comment]
I'll only be able to test it again later on. I usually start the application from within api folder with "npm run frontend", and that's giving me a lot of errors

**Comment by asantos3** [comment]
Do it inside the frontend folder but what errors it gives you?

**Comment by ghost** [comment]
My bad, never noticed that command on the api side.

**Comment by rui1974** [comment]
I'll only be able to try it around 19.00 (working now). I'll report the errors (if any)

**Pull request merged**
